project:
  type: book
  output-dir: _rendered-files

book:
  title: |
    El punto de(l) contacto: consciencia y sintonización intercinestésicas en la danza de improvisación de contacto
  output-file: "manuscrito-tesis"
  author: Esteban Fredin Ortiz
  date: last-modified
  
  chapters:
    - index.qmd
    - capítulos/1-introducción.qmd
    - capítulos/2-marco-teórico.qmd
    - capítulos/3-metodología.qmd
    - capítulos/4-resultados.qmd
    - capítulos/5-discusión.qmd
    - capítulos/6-conclusiones.qmd
    - capítulos/referencias.qmd
    
  appendices:
    - apéndices/entrevistas.qmd
    - apéndices/libro-de-códigos.qmd
    - apéndices/código-fuente.qmd

bibliography: otros-documentos/references.bib
csl: otros-documentos/apa-no-ampersand.csl

lang: es

format: 
  docx:
    reference-doc: otros-documentos/documento-de-referencia.docx

editor: source