project:
  type: book

book:
  title: "Improvisando con(-)tacto: comunicación háptica y conexión interpersonal en la danza de improvisación de contacto"
  author: "Esteban Fredin Ortiz"
  date: "5/5/2025"
  chapters:
    - index.qmd
    - introducción.qmd
    - marco-teórico.qmd
    - metodología.qmd
    - entrevistas.qmd
    - estudios.qmd
    - discusión.qmd
    - conclusiones.qmd
    - referencias.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual