# Nota sobre el lenguaje inclusivo

Este documento busca ser inclusivo en su lenguaje, lo cual introduce algunos retos en lo que refiere a la interacción entre el género gramatical y la identidad de género. Dicha cuestión sigue siendo un tema muy polémico — incluso dentro de círculos académicos dedicados al análisis lingüístico y discursivo [@becker2019; @bolívar2019; @furtado2013; @pérez-valero2019; @scotto2020] — por lo que, sin importar por cuál criterio se opte, alguien terminará desaprobando la decisión y, paradójicamente, sintiéndose víctima de una práctica de exclusión. Reconociendo que esto es inevitable, se ha optado por decepcionar de la manera más equitativa posible a todas las posturas dentro de este debate. Aunque se ha hecho el esfuerzo por utilizar construcciones gramaticales que no puedan ser percibidas como excluyentes y que a su vez estén aprobadas por la Real Academia Española, hay muchas instancias en las que esto no ha sido posible. En dichos casos se optó por utilizar la grafía "x" para remplazar los marcadores de género cuando estos se refieran a personas genéricas o hipotéticas. De esta manera, quienes lean este documento encontrarán construcciones como “xlx otrx” y “lxs bailarinxs”.

Tres críticas comunes a esta solución es que resulta impronunciable, entorpece la lectura y es estéticamente lamentable. La respuesta a la primera crítica es que ese es precisamente el punto; esta solución es la del equilibrio entre las dos posturas. La "x" en estos casos no representa un fonema sino una variable que xlx lectorx ha de despejar según su propio criterio. Así, las sensibilidades conservadoras pueden leer las formas del masculino genérico; las feministas, las del femenino y las no binarias, las que ellxs propongan. La segunda crítica es más difícil de sortear, pero desde la perspectiva de quien escribe, es más económico mecanografiar “xlx otrx” a “les, las y los otros”, que de todas formas hiere ciertas susceptibilidades. Ante la tercera crítica solo queda conceder.

Otra posible objeción es que se trata una solución tibia que evita pronunciarse a favor de la inclusión de género en el lenguaje. Otra vez, ese es también el punto de esta decisión, preservar el tono imparcial que deber caracterizar al discurso científico y académico. Hay que reconocer que esto no es óptimo, pero hoy por hoy parece que la única forma de logar cierta neutralidad es que todas las partes involucradas se sientan parcialmente excluidas.

Finalmente, habrá quien cuestione la pertinencia de este tipo de lenguaje en un trabajo académico y lo considere una falta de seriedad y formalidad. Frente a esa objeción, hay que recalcar que este es un trabajo que trata principalmente sobre la forma en la que las personas se relacionan unas con otras. El lenguaje también es una práctica relacional, por lo que reconocer la identidad de género de quienes hacen posible esta investigación es una formalidad básica y muestra de respeto y un mínimo de empatía. Este proyecto depende del trabajo y colaboración de académicxs e informantes que no consideran el uso del masculino genérico lxs incluye. La polémica del uso del lenguaje inclusivo en contextos académicos invita a la comunidad científica a considerar qué valora más: la coherencia y la integridad intelectual o la adhesión a la tradición y las jerarquías institucionales. Por parte de este autor, la decisión tomada es clara y sus criterios se han hecho explícitos.

# Prefacio {.unnumbered}

> Si pensar es un modo de frecuentar algo, y si algo del pensamiento pesa, la piel, las articulaciones, los des-equilibrios y las miradas... pueden ser algunas líneas de co-extensión entre filosofía y danza que escapen al dualismo cartesiano. — Marie Bardet

> You've been swimming in gravity since the day you were born. Every cell knows where down is. Easily forgotten. Your mass and the earth's mass calling to each other. — Steve Paxton
