# Introducción

## La improvisación de contacto

La improvisación de contacto[^1-introducción-1] (IC) es una práctica dancística originada en la década de los 70 en los Estados Unidos que tiene como fundamento la exploración del peso y la caída como principios para la improvisación del movimiento [@paxton1987]. Esta práctica tiene sus antecedentes con el Judson Dance Theater (1962-1964), un colectivo de artistas experimentales que presentaban sus piezas en la Iglesia Memorial Judson en Nueva York, inicialmente como una continuación de talleres ofrecidos por el coreógrafo y compositor Robert Ellis Dunn. El acercamiento posmoderno a la danza de este colectivo se caracterizó por la incorporación de movimientos y espacios cotidianos a la danza, la influencia de filosofías y artes marciales orientales — principalmente el budismo y el aikido — y la experimentación con nuevas técnicas de composición inspiradas en gran medida por la música de John Cage y el trabajo coreográfico de Merce Cunningham. Más tarde, varios de las y los miembros del *Judson Dance Theater* seguirían colaborando a través de *Grand Union* (1970-1976), otro colectivo que surgió de la pieza de Yvonne Rainer, *Continuous Project - Altered Daily*, una pieza en constante evolución que incluía el ensayo como parte del *performance* y hacía énfasis en la improvisación como herramienta coreográfica [@novack1990, pos. 988]. En 1972, el bailarín y coreógrafo Steve Paxton ofreció una serie de clases en *Oberlin College*, Ohio, como parte de una residencia artística con Grand Union. El material en las clases de la mañana era de carácter contemplativo. Se concentraba en llevar la atención a los micro-movimientos automáticos necesarios para mantener una posición erguida pero relajada y las sensaciones del cuerpo respondiendo a la fuerza de gravedad. Por otra parte, en las prácticas vespertinas, en las que solo se incluyeron hombres, los participantes exploraban desorientarse, rodar, chocar, saltar, caer y atrapar a sus compañeros sobre colchonetas de gimnasio. De la combinación de estas prácticas dispares surgió *Magnesium*, una pieza donde los bailarines se aventaban y atrapaban entre ellos durante 15 minutos para terminar de pie en un estado contemplativo que más tarde se denominaría “la pequeña danza” [@albright2013, 214]. Esa primavera, Paxton siguió investigando y refinando el material ahora junto con estudiantes de ambos sexos en *Bennington College* y en junio presentó *Contact Improvisations*, una pieza que tuvo lugar durante cinco tardes consecutivas en la Galería John Weber en Nueva York con miembros de Grand Union y estudiantes de Oberlin y Bennington, así como de la Universidad de Rochester. Durante esa presentación, el público entraba y salía a su gusto de la sala de exhibición mientras en la colchoneta las y los intérpretes exploraban las posibilidades de movimiento que ofrece caer[@novack1990, pos. 1123].

[^1-introducción-1]: Traducido del inglés “*contact improvisation''*. En español, a esta práctica se le suele llamar *contact*, *contact* improvisación, contacto improvisación o danza de contacto. A lo largo de este texto me ceñiré al consenso al que se llegó en 2019 durante el 4° Encuentro de Improvisación de Contacto en México y me referiré a esta práctica como improvisación de contacto, ya que es una traducción íntegra y gramaticalmente correcta del término.

Los principios de movimiento descubiertos y trabajados durante ese año de investigación serían el germen de la improvisación de contacto. Durante las siguientes décadas, varias personas que participaron de esas experiencias iniciales siguieron investigando, refinando y enseñando el material a distintos públicos. Con el tiempo, las colchonetas desaparecieron y la práctica en gran medida se centró en preservar y mover el punto de contacto entre bailarines, así como la comunicación háptica a partir de compartir peso con otras personas en un estado de *flow*. Además, la inclusión de técnicas somáticas, es decir, prácticas que estudian el cuerpo desde la experiencia vivida como el método Feldenkrais y el *Body Mind Centering*, han probado ser importantes para la improvisación de contacto, ya que ayudan a cultivar la atención a las sensaciones corporales por encima de lograr resultados específicos o replicar ciertos patrones de movimiento [@paxton2003]. Si bien la influencia de la improvisación de contacto aún es palpable en la danza contemporánea, sobre todo en el *partnering*, su mayor impacto ha sido fuera de las escuelas de danza y las compañías profesionales [@novack1990, pos.1751]. La práctica ha atraído a un público global y heterogéneo — muchas veces sin entrenamiento formal en danza — interesado en el movimiento y nuevas formas de relacionarse con y a través de su corporalidad. La improvisación de contacto suele bailarse en sesiones informales de danza llamadas *jams* [@novack1990, pos. 331], así como en clases y talleres impartidos por una comunidad de enseñanza global tejida de forma horizontal sin ninguna institución reguladora de por medio. Aún sin una institución rectora, la improvisación de contacto ha pervivido por más de cinco décadas y se ha extendido miles de kilómetros más allá del nicho contracultural que le dio origen, convirtiéndose en un fenómeno global que, más que un estilo de danza, es una práctica relacional de cuerpos en movimiento.

Curt Siddall, uno de los participantes en los experimentos iniciales de la IC, dio en 1975 una de las primeras definiciones de esta danza: “Contact Improvisation is a movement form, improvisational in nature, involving two bodies in contact. Impulses, weight, and momentum are communicated through a point of physical contact that continually rolls across and around the bodies of the dancers” [La improvisación de contacto es una forma de movimiento, en esencia imporvisado, que involucra dos cuerpos en contacto. Los impulsos, el peso y la inercia son comunicados a través de un punto de contacto físico que rueda continuamente por los cuerpos de quienes bailan] [citado en @koteen2008, p. xiii]. También en 1975, con el objetivo de seguir compartiendo información de forma descentralizada y tejer una red horizontal de practicantes, se creó la revista especializada *Contact Quarterly* (antes *Contact Newsletter*) [@paxton2022]. Su primera editora, Nancy Stark Smith, fue una de las estudiantes de Steve Paxton en Oberlin y se convirtió en una de las figuras centrales en la enseñanza y difusión de la improvisación de contacto hasta su muerte en 2020. Ahora la revista es editada por Lisa Nelson en formato exclusivamente digital. Este importante acervo es de gran utilidad, tanto como material historiográfico como inspiración teórico-práctica y corpus de trabajo.

## La sintonización interpersonal

### Sintonización intercinestésica

### Sintonización fisiológica

### Vinculación con los PRONACEs
