# Marco teórico

Esquema del marco teórico
Al tratarse de un estudio sobre la experiencia, este se enmarca fácilmente dentro de la fenomenología entendida, más allá de cierta tradición filosófica, como un conjunto de teorías y métodos para el estudio de la experiencia vivida. Sin embargo, el problema también está dado en términos cognitivos — procesos atencionales y conciencia intercinestésica —, psicológicos — sentido de agencia, empatía — así como cuestiones semióticas, es decir, fenómenos de comunicación y significación. Por lo tanto, es útil situarse desde un paradigma teórico que pueda de integrar conceptos y metodologías de estas diferentes disciplinas. La semiótica cognitiva, es un paradigma capaz de hacer esto.
La semiótica cognitiva
Si bien, como apunta Goran Sonesson (2012), el término “semiótica cognitiva” se ha acuñado múltiples veces en las últimas décadas (p. 208), en este caso en particular se está haciendo referencia a una corriente de pensamiento que tiene su origen en los países nórdicos, especialmente la Universidad de Aarhus en la década de los 90 (Bundgård et al., 2006), la cual fue distanciándose cada vez más de la semiótica estructuralista y encontrando nuevas afinidades en inspiración en disciplinas como la lingüística y la psicología cognitivas, la fenomenología y las neurociencias. Jordan Zlatev (2015), profesor de semiótica cognitiva en la Universidad de Lund, explica que este se trata de un campo transdisciplinario que busca explorar fenómenos de significación integrando los métodos y teorías de las ciencias cognitivas con los de la semiótica y las humanidades (p. 1043).
Por lo tanto, el término ‘semiótica cognitiva’ no hace referencia a una subdisciplina dentro de la semiótica general (como lo son la zoosemiótica o la semiótica cultural), ni una modalidad específica (como la semiótica visual o la textual). De igual manera, no se trata de un linaje o escuela en particular (peirceano, saussureano, greimasiano, etc.). Tampoco se trata de una teoría en particular u otra manera de referirse a las ciencias cognitivas. 
Si bien esta caracterización en términos negativos es útil para delinear la semiótica cognitiva, Zlatev (2015) también menciona algunos campos de estudio que han realizado contribuciones importantes a la semiótica cognitiva, como la semántica cognitiva (Langacker, 1987; Talmy, 2000; Lakoff y Johnson, 1980, 1999; Fauconnier y Turner, 2002), estudios sobre la gestualidad (Kendon, 2004; Cienki y Müller, 2008; McNeill, 2012), teorías sobre el desarrollo semiótico en la infancia (Piaget, 1962; Vigotski, 1962, 1978), la evolución biocultural (Donald, 1991, 2001; Deacon, 1997, 2012; Tomasello, 1999, 2003, 2008), y la teoría de la mente corporeizada (embodied mind) (Varela et al., 2017;  Dan Zahavi, 2001; Shaun Gallager, 2005, Gallager y Zahavi, 2008) (pp. 1045-52). 
Zlatev (2015) menciona cinco aspectos que caracterizan a la semiótica cognitiva: 
1.	Bucle conceptual-empírico – la solución de problemas conceptuales va de la mano con la investigación empírica y ambos aspectos se informan mutuamente. Por ejemplo: estudiar la experiencia de lxs bailarinxs de improvisación de contacto nos ayuda a definir y precisar conceptos como la agencia conjunta y viceversa.
2.	Triangulación metodológica – la semiótica cognitiva se nutre de estudios que utilizan diversas perspectivas y metodologías: en primera persona o subjetivas, como investigaciones fenomenológicas; en segunda persona o intersubjetivas como entrevistas; y en tercera persona u objetivas, como los experimentos científicos.
3.	Influencia de la fenomenología – tomar la experiencia vivida como punto de partida. Varios estudios en semiótica cognitiva tienen cierta deuda intelectual o afinidad por la fenomenología. 
4.	Dinamismo semiótico – los fenómenos de significación son concebidos como procesos dinámicos y no objetos estáticos. Entender los procesos semióticos es más importante que la catalogación de signos. 
5.	Transdisciplinariedad – la semiótica cognitiva entiende que los fenómenos de significación no constituyen un dominio empírico específico, sino que se encuentran entre, a través y más allá de cualquier disciplina académica individual (pp. 1058-63).
Estas características no han de entenderse como una lista de requisitos sino una descripción prototípica del tipo de investigación que podría denominarse semiótica cognitiva.
Cognición 4E: encarnada, embebida, enactiva y extendida
La semiótica cognitiva forma parte de un cambio epistemológico dentro de las ciencias cognitivas que se ha estado gestando desde la década de los 80, el cual resalta la importancia de la corporalidad o encarnación (embodiment) en los procesos de atención, percepción, acción, memoria, etc. (Varela et al., 2017; Lakoff y Johnson, 1999; Noë, 2010, Newen et al., 2018). Esto ha dado pie a lo que hoy se denomina como 4E cognition, una abreviatura de embodied, embedded, enactive and extended cognition. 
Este paradigma ha cuestionado ampliamente la división cartesiana entre res extensa y res cogitans, lo físico y lo psíquico, argumentando y encontrando evidencias a favor de la unidad de mente y cuerpo. Sus proponentes argumentan que los organismos no son arrojados a un entorno preexistente que luego deben interpretar; más bien, estos enactúan o gestan sus propios mundos vividos a través de la interacción de su corporalidad con el entorno, el cual no tiene una existencia independiente. Así, no existe una realidad externa que el organismo necesite o pueda representar internamente, sino diferentes formas de percibir y actuar en el mundo a través de la corporalidad (Varela et al., 2017).
Bajo este posicionamiento teórico, se dice que la cognición, además de ser corporeizada y enactiva, también está embebida o situada. Esto hace énfasis en su carácter pragmático. La cognición nunca ocurre en el vacío, sino dentro de contextos y entornos específicos — tanto físicos como sociales (Beer, 2014; Huebner, 2013). Esto lleva al último componente, la cognición es extendida (Clark y Chalmers, 1998), porque involucra a objetos e incluso otras personas (Gallagher, 2013), no solo como herramientas o apoyos para la cognición sino como parte integral de ésta. 
Finalmente, cabe recalcar que la cognición 4E es una denominación muy amplia que no designa una postura uniforme, sino diversas propuestas teóricas y metodológicas que a menudo presentan diferencias importantes e incompatibilidades.  Por lo tanto, su criterio de pertenencia no es su consistencia o concordancia mutuas, sino la importancia que le otorgan a experiencia vivida y su posicionamiento crítico frente a teorías y modelos de la mente como representación y manipulación simbólica o como una propiedad emergente de la activación de redes neuronales biológicas o artificiales. 
La neurofenomenología
Dadas las características del paradigma epistemológico de la cognición 4E, la fenomenología se ha vuelto una herramienta de investigación importante (Varela, 1996; Gallagher y Zahavi, 2012). El neurocientífico chileno, Francisco Varela (1996), un pensador clave dentro del enactivismo, articuló la idea de la neurofenomenología como una posible respuesta metodológica al ‘problema difícil de la consciencia’ planteado por el filósofo de la mente australiano, David Chalmers (1995).  Este último argumenta que la neurociencia está teniendo éxito en resolver los problemas “fáciles” de la consciencia. Estos consisten en explicar los mecanismos neurológicos y cognitivo-conductuales aledaños a ciertas facetas de la experiencia como la percepción, la atención, la memoria, etc. Sin embargo, para Chalmers explicar cómo y por qué existe una experiencia fenoménica es el problema difícil de la consciencia y éste es, a su juicio, irresoluble, lo que lo ha llevado a propugnar un dualismo naturalista donde la brecha entre el mundo de la experiencia subjetivo y los hechos objetivos es insoslayable.
Para Varela, la solución a este problema difícil se encuentra en la mutua reciprocidad y diálogo entre los métodos y hallazgos cuantitativos en tercera persona de las ciencias cognitivas y los métodos y descripciones de la experiencia en primera persona de la fenomenología, así como de otras tradiciones filosóficas y contemplativas que han desarrollado en alto grado el estudio de la consciencia (Shear y Varela, 1999). De esta forma, tanto lxs investigadores y sujetos experimentales tendrían que estar entrenados en técnicas para atender a su propia atención. Varela anticipaba que esta alternativa sería un mayor reto que los problemas “fáciles”, ya que no solo requiere de avances tecnológicos o científicos, sino de un cambio de paradigma por parte de la comunidad científica, uno que tome en serio la experiencia subjetiva y no la reduzca a un epifenómeno de causas objetivas y a explicaciones mecanicistas.
La neurofenomenología considera que describir la experiencia vivida resulta tan crucial como identificar las estructuras neuronales involucradas y las conductas observables en tal o cual proceso cognitivo. El cuerpo ya no es entendido como el correlato objetivo de la mente o un objeto más en un mundo de objetos, sino como un requisito crucial de la experiencia misma. En efecto, la experiencia “subjetiva” es el punto de partida que permite adquirir y dar sentido a los resultados “objetivos”. Por otra parte, este acercamiento fenomenológico no es una reificación contemporánea de las ideas de Husserl — aunque sí toma inspiración de ellas — ni un retorno a la psicología introspectiva de finales del siglo XIX; no es un retraerse del mundo para mirar adentro, sino el estudio descriptivo metódico y colegialmente validado de la experiencia del cuerpo enactuando su entorno. 



## La semiótica cognitiva

## La cognición 5e

### La cardiofenomenología

### La entrevista micro-fenomenológica

### La lingüística cognitiva


