# Notas

Notas que no son de aquí o allá. Quizá encuentren su camino al manuscrito de la tesis, quizá no.

## Sobre el sentido del tacto

El sentido del tacto es primordial.

Dicha aseveración es cierta tanto en términos evolutivos como de desarrollo.

Sin embargo, en términos tanto cognitivos como semióticos es una modalidad relativamente poco estudiada, en especial si se le compara con lo que se conoce hoy día acerca de la visión y la audición. A menudo ignorado, el tacto hace al mundo tangible.

M. Fulkerson , que es el tacto -\> expandir a lo háptico para incorporar propiocepción y cinestesia

El oido parece haber evolucionado de celulas que percibian la gravedad en vertebrados, y sensores de estiramiento en insectos.

Tacto y afecto, apego los estudios de Harry Harlow con macacos de rhesus

Daniel Stern y su trabajo con madres y bebés a menudo aludido por S. Paxton.

## Esto lo puedo guardar para cuando introduzca la semántica cognitiva

El científico cognitivo Raymond Gibbs Jr. (2003) considera que la teoría de la metáfora conceptual (TMC), proveniente de la lingüística cognitiva, puede explicar cómo el público le da significado a una danza de improvisación de contacto. La TMC propone que el lenguaje metafórico, más allá de ser un recurso poético, es una ventana a las estructuras preconceptuales que organizan la experiencia humana y que se origina en la interacción corporal con el entorno (Lakoff y Johnson, 1980). El análisis original de Lakoff y Johnson deja de lado ejemplos claros de metáforas y se centra en figuras de habla tan sedimentadas que cuesta trabajo reconocerlas como metafóricas. Gibbs postula que la esquematización de la experiencia corpórea del arriba y el abajo se ve especialmente implicada en la interpretación de la improvisación de contacto. Uno suele asociar ‘arriba’ con felicidad, estar consciente, salud y vida. De forma conversa, el concepto de ‘abajo’ se asocia con tristeza, estar inconsciente, enfermedad y muerte. Gibbs no argumenta que quienes bailan utilizan estas equivalencias — algo cliché — para componer o comunicar algo a la audiencia, sino que estas metáforas forman la base de una experiencia común a todas las personas involucradas y, por lo tanto, un marco de referencia que permite interpretar la danza incluso si estas asociaciones se ven subvertidas por quién está bailando cuando, por ejemplo, se cae riendo.

## Partes quitadas de la introducción

### Cosas de género

Ann Cooper Albright, en su compendio de ensayos Engaging Bodies: The Politics and Poetics of Corporeality (2013), dedica varios textos a explorar la improvisación de contacto desde una perspectiva fenomenológica informada por los estudios de género. En su ensayo introductorio, enfatiza el potencial de esta forma de danza para poner en práctica lo que se teoriza en el aula. Por ejemplo, Albright equipara la desorientación espacial común en la improvisación de contacto con la desorientación que las identidades queer producen en el esquema heteronormativo (p.14) y cierra su ensayo enfatizando cómo las maneras en que pensamos sobre el mundo afectan la forma en la que nos movemos a través de éste. En otro texto, Albright identifica a la improvisación de contacto junto con la capoeira --- otra práctica corporal que no encaja fácilmente en categorías tradicionales: danza, deporte, arte marcial, ensamble musical, reunión social --- como prácticas de resistencia en las que puede haber una confrontación con otras personas y, no obstante, las diferencias de sexo, género, raza, edad y capacidad pueden ser reconocidas, celebradas y movilizadas en el cuerpo (pp. 218-229).
